const common = [];

const mobile = [
  {
    key: "custom_margin_top",
    type: "number_input",
    label: "Top Padding",
    initial_value: 0,
  },
  {
    key: "user_image_placeholder",
    type: "uploader",
    label: "User Image Placeholder",
    placeholder: "Upload an image",
  },
  {
    key: "user_image_bottom_margin",
    type: "number_input",
    label: "User Image Bottom Margin",
    label_tooltip: "Bottom margin for user image",
    initial_value: 23,
  },
  {
    group: true,
    label: "Login Button 1 Styles",
    tooltip: "Use these fields to customize Login button #1",
    folded: true,
    fields: [
      {
        key: "button_1_login_type",
        type: "select",
        options: [
          { text: "Inplayer", value: "in_player" },
          { text: "Cleeng", value: "cleeng" },
          { text: "Adobe primetime", value: "adobe_primetime" },
          { text: "Oauth2", value: "oauth_2" },
          { text: "Other", value: "other" },
        ],
        initial_value: "oauth_2",
        mandatory: true,
        label: "Select Login Type",
        tooltip:
          "Select the Login provider you would like to connect to the login button",
        placeholder: "Select login type",
      },
      {
        key: "button_1_background_image",
        type: "uploader",
        label: "Button Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_1_background_image_focused",
        type: "uploader",
        label: "Button Focused Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_1_custom_screen_id",
        type: "screen_selector",
        initial_value: "",
        tooltip:
          "In case you have more then one screen of the same provider, select which screen the button will open",
        label: "Screen",
      },
      {
        key: "button_1_custom_namespace",
        type: "text_input",
        initial_value: "",
        label: "Plugin Namespace",
        tooltip:
          "When choosing a provider that is not in the list, you will need to provide the plugin namespace. This will be used to trigger the screen when user will click the login button, or to logout when user will click the logout button. Consult with support or your plugin developer.",
        placeholder: "Custom plugin namespace",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_1_login_type",
          },
        ],
      },
      {
        key: "button_1_custom_token_key",
        type: "text_input",
        tooltip:
          "When choosing a provider that is not in the list, you will need to provide the token key. This key will be used to detremine if a user is logged in or not",
        initial_value: "",
        label: "Plugin Token Key",
        placeholder: "Custom plugin token key",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_1_login_type",
          },
        ],
      },
      {
        key: "button_1_custom_user_id_key",
        type: "text_input",
        initial_value: "",
        label: "User ID Key",
        tooltip:
          "When choosing a provider that is not in the list, providing this value will provide the component the user ID to present.",
        placeholder: "Custom user ID key",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_1_login_type",
          },
        ],
      },
      {
        key: "button_1_width",
        type: "number_input",
        label: "Button Width",
        initial_value: 239,
      },
      {
        key: "button_1_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        initial_value: 12,
      },
      {
        key: "button_1_radius",
        type: "number_input",
        label: "Button Radius",
        initial_value: 16,
      },
      {
        key: "button_1_border",
        type: "number_input",
        label: "Button Border",
        initial_value: 0,
      },
      {
        key: "button_1_border_color",
        type: "color_picker_rgba",
        label: "Button Border Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_1_border_color_focused",
        type: "color_picker_rgba",
        label: "Button Border Focused",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_1_background_color",
        type: "color_picker_rgba",
        label: "Background Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_1_background_color_focused",
        type: "color_picker_rgba",
        label: "Background Focused Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_1_title_color",
        type: "color_picker_rgba",
        label: "Title Color",
        initial_value: "#161b29FF",
      },
      {
        key: "button_1_title_color_focused",
        type: "color_picker_rgba",
        label: "Title Focused Color",
        initial_value: "#161b29FF",
      },
      {
        key: "button_1_title_text_font_android",
        type: "android_font_selector",
        label: "Android Title Font",
        initial_value: "Roboto-Bold",
      },
      {
        key: "button_1_title_text_font_ios",
        type: "ios_font_selector",
        label: "iOS Title Font",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "button_1_title_text_fontsize",
        type: "number_input",
        label: "Font size",
        initial_value: 12,
      },
    ],
  },
  {
    group: true,
    label: "Login Button 2 Styles",
    tooltip: "Use these fields to customize Login button #2",
    folded: true,
    fields: [
      {
        key: "button_2_login_enabled",
        label: "Switch to Enable Login Button 2",
        type: "switch",
        initial_value: false,
      },
      {
        key: "button_2_login_type",
        type: "select",
        options: [
          { text: "Inplayer", value: "in_player" },
          { text: "Cleeng", value: "cleeng" },
          { text: "Adobe primetime", value: "adobe_primetime" },
          { text: "Oauth2", value: "oauth_2" },
          { text: "Other", value: "other" },
        ],
        initial_value: "oauth_2",
        mandatory: true,
        label: "Select Login Type",
        placeholder: "Select login type",
      },
      {
        key: "button_2_background_image",
        type: "uploader",
        label: "Button Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_2_background_image_focused",
        type: "uploader",
        label: "Button Background Focused Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_2_custom_screen_id",
        type: "screen_selector",
        initial_value: "",
        tooltip:
          "In case you have more then one screen of the same provider, select which screen the button will open",
        label: "Screen",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_2_login_type",
          },
        ],
      },
      {
        key: "button_2_custom_namespace",
        type: "text_input",
        initial_value: "",
        label: "Plugin Namespace",
        tooltip:
          "When choosing a provider that is not in the list, you will need to provide the plugin namespace. This will be used to trigger the screen when user will click the login button, or to logout when user will click the logout button. Consult with support or your plugin developer.",
        placeholder: "Custom plugin namespace",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_2_login_type",
          },
        ],
      },
      {
        key: "button_2_custom_token_key",
        type: "text_input",
        tooltip:
          "When choosing a provider that is not in the list, you will need to provide the token key. This key will be used to detremine if a user is logged in or not",
        initial_value: "",
        label: "Plugin Token Key",
        placeholder: "Custom plugin token key",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_2_login_type",
          },
        ],
      },
      {
        key: "button_2_custom_user_id_key",
        type: "text_input",
        initial_value: "",
        label: "User ID Key",
        tooltip:
          "When choosing a provider that is not in the list, providing this value will provide the component the user ID to present.",
        placeholder: "Custom user ID key",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_2_login_type",
          },
        ],
      },
      {
        key: "button_2_width",
        type: "number_input",
        label: "Button Width",
        initial_value: 239,
      },
      {
        key: "button_2_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        initial_value: 12,
      },
      {
        key: "button_2_radius",
        type: "number_input",
        label: "Button Radius",
        initial_value: 16,
      },
      {
        key: "button_2_border",
        type: "number_input",
        label: "Button Border",
        initial_value: 1,
      },
      {
        key: "button_2_border_color",
        type: "color_picker_rgba",
        label: "Button Border Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_2_border_color_focused",
        type: "color_picker_rgba",
        label: "Button Border Focused Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_2_background_color",
        type: "color_picker_rgba",
        label: "Background Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_2_background_color_focused",
        type: "color_picker_rgba",
        label: "Background Focused Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_2_title_color",
        type: "color_picker_rgba",
        label: "Title Color",
        initial_value: "#161b29FF",
      },
      {
        key: "button_2_title_color_focused",
        type: "color_picker_rgba",
        label: "Title Focused Color",
        initial_value: "#161b29FF",
      },
      {
        key: "button_2_title_text_font_android",
        type: "android_font_selector",
        label: "Android Title Font",
        initial_value: "Roboto-Bold",
      },
      {
        key: "button_2_title_text_font_ios",
        type: "ios_font_selector",
        label: "iOS Title Font",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "button_2_title_text_fontsize",
        type: "number_input",
        label: "Font Size",
        initial_value: 12,
      },
    ],
  },
  {
    group: true,
    label: "Info View Styles",
    tooltip: "These fields affect information views",
    folded: true,
    fields: [
      {
        key: "info_label_title_color",
        type: "color_picker_rgba",
        label: "Title Color",
        initial_value: "#ffffffff",
      },
      {
        key: "info_label_title_text_font_android",
        type: "android_font_selector",
        label: "Android Title Font",
        initial_value: "Roboto-Bold",
      },
      {
        key: "info_label_title_text_font_ios",
        type: "ios_font_selector",
        label: "iOS Title Font",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "info_label_title_text_fontsize",
        type: "number_input",
        label: "Font Size",
        label_tooltip: "Font size for the title",
        initial_value: 16,
      },
      {
        key: "info_label_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        label_tooltip: "Bottom margin for button",
        initial_value: 5,
      },
      {
        key: "info_label_description_title_color",
        type: "color_picker_rgba",
        label: "Description Color",
        initial_value: "#161b29B3",
      },
      {
        key: "info_label_description_title_text_font_android",
        type: "android_font_selector",
        label: "Android Description Font",
        initial_value: "Roboto-Bold",
      },
      {
        key: "info_label_description_title_text_font_ios",
        type: "ios_font_selector",
        label: "iOS Description Font",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "info_label_description_title_text_fontsize",
        type: "number_input",
        label: "Description Font Size",
        initial_value: 12,
      },
      {
        key: "info_label_description_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        initial_value: 5,
      },
    ],
  },
  {
    group: true,
    label: "Logout Button Styles",
    tooltip: "These fields affect small logout button styles",
    folded: true,
    fields: [
      {
        key: "button_logout_background_image",
        type: "uploader",
        label: "Button Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_logout_background_image_focused",
        type: "uploader",
        label: "Button Focused Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_logout_width",
        type: "number_input",
        label: "Button Width",
        initial_value: 99,
      },
      {
        key: "button_logout_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        initial_value: 12,
      },
      {
        key: "button_logout_radius",
        type: "number_input",
        label: "Button Radius",
        initial_value: 13,
      },
      {
        key: "button_logout_border",
        type: "number_input",
        label: "Button Border",
        initial_value: 1,
      },
      {
        key: "button_logout_border_color",
        type: "color_picker_rgba",
        label: "Button Border Color",
        initial_value: "#979797ff",
      },
      {
        key: "button_logout_border_color_focused",
        type: "color_picker_rgba",
        label: "Button Border Focused Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_logout_background_color",
        type: "color_picker_rgba",
        label: "Background Color",
        label_tooltip: "Background color for the toggle component",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_logout_background_color_focused",
        type: "color_picker_rgba",
        label: "Background Focused Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_logout_title_color",
        type: "color_picker_rgba",
        label: "Title Color",
        initial_value: "#979797FF",
      },
      {
        key: "button_logout_title_color_focused",
        type: "color_picker_rgba",
        label: "Title Focused Color",
        initial_value: "#979797FF",
      },
      {
        key: "button_logout_title_text_font_android",
        type: "android_font_selector",
        label: "Android Title Font",
        initial_value: "Roboto-Bold",
      },
      {
        key: "button_logout_title_text_font_ios",
        type: "ios_font_selector",
        label: "iOS Title Font",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "button_logout_title_text_fontsize",
        type: "number_input",
        label: "Font Size",
        initial_value: 10,
      },
    ],
  },
  {
    group: true,
    label: "Logout Big Button Styles",
    tooltip: "These fields affect big logout button styles",
    folded: true,
    fields: [
      {
        key: "button_logout_big_background_image",
        type: "uploader",
        label: "Button Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_logout_big_background_image_focused",
        type: "uploader",
        label: "Button Focused Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_logout_big_width",
        type: "number_input",
        label: "Button Width",
        initial_value: 239,
      },
      {
        key: "button_logout_big_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        initial_value: 12,
      },
      {
        key: "button_logout_big_radius",
        type: "number_input",
        label: "Button Radius",
        initial_value: 13,
      },
      {
        key: "button_logout_big_border",
        type: "number_input",
        label: "Button Border",
        initial_value: 1,
      },
      {
        key: "button_logout_big_border_color",
        type: "color_picker_rgba",
        label: "Button Border Color",
        initial_value: "#979797ff",
      },
      {
        key: "button_logout_big_border_color_focused",
        type: "color_picker_rgba",
        label: "Button Border Focused Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_logout_big_background_color",
        type: "color_picker_rgba",
        label: "Background Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_logout_big_background_color_focused",
        type: "color_picker_rgba",
        label: "Background Focused Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_logout_big_title_color",
        type: "color_picker_rgba",
        label: "Title Color",
        initial_value: "#979797FF",
      },
      {
        key: "button_logout_big_title_color_focused",
        type: "color_picker_rgba",
        label: "Title Focused Color",
        initial_value: "#979797FF",
      },
      {
        key: "button_logout_big_title_text_font_android",
        type: "android_font_selector",
        label: "Android Title Font",
        initial_value: "Roboto-Bold",
      },
      {
        key: "button_logout_big_title_text_font_ios",
        type: "ios_font_selector",
        label: "iOS Title Font",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "button_logout_big_title_text_fontsize",
        type: "number_input",
        label: "Font Size",
        initial_value: "12",
      },
    ],
  },
  {
    group: true,
    label: "Debug",
    tooltip: "For development purposes",
    folded: true,
    fields: [
      {
        type: "tag_select",
        key: "debug_dummy_data_source",
        tooltip_text: "Use dummy data source to test UI",
        options: [
          {
            text: "On",
            value: "on",
          },
          {
            text: "Off",
            value: "off",
          },
        ],
        initial_value: "off",
      },
    ],
  },
];

const tv = [
  {
    key: "custom_margin_top",
    type: "number_input",
    label: "Top Padding",
    initial_value: 100,
  },
  {
    key: "user_image_placeholder",
    type: "uploader",
    label: "User Image Placeholder",
    placeholder: "Upload a file",
  },
  {
    key: "user_image_bottom_margin",
    type: "number_input",
    label: "User Image Bottom Margin",
    label_tooltip: "Bottom margin for user image",
    initial_value: 35,
  },
  {
    group: true,
    label: "Login Button 1 Styles",
    tooltip: "Use these fields to customize Login button #1",
    folded: true,
    fields: [
      {
        key: "button_1_login_type",
        type: "select",
        options: [
          { text: "Inplayer", value: "in_player" },
          { text: "Cleeng", value: "cleeng" },
          { text: "Adobe primetime", value: "adobe_primetime" },
          { text: "Oauth2", value: "oauth_2_tv" },
          { text: "Other", value: "other" },
        ],
        initial_value: "oauth_2",
        mandatory: true,
        tooltip:
          "Select the Login provider you would like to connect to the login button",
        label: "Select Login Type",
        placeholder: "Select login type",
      },
      {
        key: "button_1_background_image",
        type: "uploader",
        label: "Button Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_1_background_image_focused",
        type: "uploader",
        label: "Button Focused Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_1_custom_screen_id",
        type: "screen_selector",
        initial_value: "",
        label: "Screen",
        tooltip:
          "In case you have more then one screen of the same provider, select which screen the button will open",
      },
      {
        key: "button_1_custom_namespace",
        type: "text_input",
        initial_value: "",
        label: "Plugin Namespace",
        placeholder: "Custom plugin namespace",
        tooltip:
          "When choosing a provider that is not in the list, you will need to provide the plugin namespace. This will be used to trigger the screen when user will click the login button, or to logout when user will click the logout button. Consult with support or your plugin developer.",
        placeholder: "Custom plugin namespace",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_1_login_type",
          },
        ],
      },
      {
        key: "button_1_custom_token_key",
        type: "text_input",
        tooltip:
          "When choosing a provider that is not in the list, you will need to provide the token key. This key will be used to detremine if a user is logged in or not",
        initial_value: "",
        label: "Plugin Token Key",
        placeholder: "Custom plugin token key",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_1_login_type",
          },
        ],
      },
      {
        key: "button_1_custom_user_id_key",
        type: "text_input",
        initial_value: "",
        label: "User ID Key",
        tooltip:
          "When choosing a provider that is not in the list, providing this value will provide the component the user ID to present.",
        placeholder: "Custom user ID key",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_1_login_type",
          },
        ],
      },
      {
        key: "button_1_width",
        type: "number_input",
        label: "Button Width",
        initial_value: 544,
      },
      {
        key: "button_1_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        initial_value: 27,
      },
      {
        key: "button_1_radius",
        type: "number_input",
        label: "Button Radius",
        initial_value: 16,
      },
      {
        key: "button_1_border",
        type: "number_input",
        label: "Button Border",
        initial_value: 0,
      },
      {
        key: "button_1_border_color",
        type: "color_picker_rgba",
        label: "Button Border Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_1_border_color_focused",
        type: "color_picker_rgba",
        label: "Button Border Focused",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_1_background_color",
        type: "color_picker_rgba",
        label: "Background Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_1_background_color_focused",
        type: "color_picker_rgba",
        label: "Background Focused Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_1_title_color",
        type: "color_picker_rgba",
        label: "Title Color",
        initial_value: "#161b29FF",
      },
      {
        key: "button_1_title_color_focused",
        type: "color_picker_rgba",
        label: "Title Focused Color",
        initial_value: "#161b29FF",
      },
      {
        key: "button_1_title_text_font_android_tv",
        type: "android_font_selector",
        label: "Title Font Android",
        label_tooltip: "Font for the toggle title for Android",
        initial_value: "Roboto-Bold",
      },
      {
        key: "button_1_title_text_font_tvos",
        type: "tvos_font_selector",
        label: "TVOS Title Font",
        label_tooltip: "Font for the toggle title for TVOS",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "button_1_title_text_font_lg_tv",
        type: "lg_tv_font_selector",
        label: "LG TV Title Font",
        label_tooltip: "Font for the toggle title for LG TV",
        initial_value: "Museo-Bold",
      },
      {
        key: "button_1_title_text_font_samsung_tv",
        type: "samsung_font_selector",
        label: "Samsung TV Title Font",
        label_tooltip: "Font for the toggle title for Samsung TV",
        initial_value: "SamsungOneUI-Bold",
      },
      {
        key: "button_1_title_text_fontsize",
        type: "number_input",
        label: "Font Size",
        label_tooltip: "Font size toggle title",
        initial_value: 29,
      },
    ],
  },
  {
    group: true,
    label: "Login Button 2 Styles",
    tooltip: "Use these fields to customize Login button #2",
    folded: true,
    fields: [
      {
        key: "button_2_login_enabled",
        label: "Switch to Enable Login Button 2",
        type: "switch",
        initial_value: false,
      },
      {
        key: "button_2_login_type",
        type: "select",
        options: [
          { text: "Inplayer", value: "in_player" },
          { text: "Cleeng", value: "cleeng" },
          { text: "Adobe primetime", value: "adobe_primetime" },
          { text: "Oauth2", value: "oauth_2_tv" },
          { text: "Other", value: "other" },
        ],
        initial_value: "oauth_2",
        mandatory: true,
        label: "Select Login Type",
        placeholder: "Select login type",
      },
      {
        key: "button_2_background_image",
        type: "uploader",
        label: "Button Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_2_background_image_focused",
        type: "uploader",
        label: "Button Focused Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_2_custom_screen_id",
        type: "screen_selector",
        initial_value: "",
        tooltip:
          "In case you have more then one screen of the same provider, select which screen the button will open",
        label: "Screen",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_2_login_type",
          },
        ],
      },
      {
        key: "button_2_custom_namespace",
        type: "text_input",
        initial_value: "",
        label: "Plugin Namespace",
        tooltip:
          "When choosing a provider that is not in the list, you will need to provide the plugin namespace. This will be used to trigger the screen when user will click the login button, or to logout when user will click the logout button. Consult with support or your plugin developer.",
        placeholder: "Custom plugin namespace",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_2_login_type",
          },
        ],
      },
      {
        key: "button_2_custom_token_key",
        type: "text_input",
        tooltip:
          "When choosing a provider that is not in the list, you will need to provide the token key. This key will be used to detremine if a user is logged in or not",
        initial_value: "",
        label: "Plugin Token Key",
        placeholder: "Custom plugin token key",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_2_login_type",
          },
        ],
      },
      {
        key: "button_2_custom_user_id_key",
        type: "text_input",
        initial_value: "",
        label: "User ID Key",
        tooltip:
          "When choosing a provider that is not in the list, providing this value will provide the component the user ID to present.",
        placeholder: "Custom user ID key",
        conditional_fields: [
          {
            condition_value: ["other"],
            key: "styles/button_2_login_type",
          },
        ],
      },
      {
        key: "button_2_width",
        type: "number_input",
        label: "Button Width",
        initial_value: 544,
      },
      {
        key: "button_2_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        initial_value: 27,
      },
      {
        key: "button_2_radius",
        type: "number_input",
        label: "Button Radius",
        initial_value: 16,
      },
      {
        key: "button_2_border",
        type: "number_input",
        label: "Button Border",
        initial_value: 1,
      },
      {
        key: "button_2_border_color",
        type: "color_picker_rgba",
        label: "Button Border Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_2_border_color_focused",
        type: "color_picker_rgba",
        label: "Button Border Focused Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_2_background_color",
        type: "color_picker_rgba",
        label: "Background Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_2_background_color_focused",
        type: "color_picker_rgba",
        label: "Focused Background Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_2_title_color",
        type: "color_picker_rgba",
        label: "Title Color",
        initial_value: "#161b29FF",
      },
      {
        key: "button_2_title_color_focused",
        type: "color_picker_rgba",
        label: "Title Focused Color",
        initial_value: "#161b29FF",
      },
      {
        key: "button_2_title_text_font_android_tv",
        type: "android_font_selector",
        label: "Android Title Font",
        initial_value: "Roboto-Bold",
      },
      {
        key: "button_2_title_text_font_tvos",
        type: "tvos_font_selector",
        label: "tvOS Title Font",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "button_2_title_text_font_lg_tv",
        type: "lg_tv_font_selector",
        label: "LG TV Title Font",
        initial_value: "Museo-Bold",
      },
      {
        key: "button_2_title_text_font_samsung_tv",
        type: "samsung_font_selector",
        label: "Samsung TV Title Font",
        initial_value: "SamsungOneUI-Bold",
      },
      {
        key: "button_2_title_text_fontsize",
        type: "number_input",
        label: "Font Size",
        initial_value: 29,
      },
    ],
  },
  {
    group: true,
    label: "Info View Styles",
    tooltip: "These fields affect information views",
    folded: true,
    fields: [
      {
        key: "info_label_title_color",
        type: "color_picker_rgba",
        label: "Title Color",
        initial_value: "#ffffffff",
      },
      {
        key: "info_label_title_text_font_android_tv",
        type: "android_font_selector",
        label: "Title Font Android TV",
        label_tooltip: "Font for the toggle title for Android TV",
        initial_value: "Roboto-Bold",
      },
      {
        key: "info_label_title_text_font_ios",
        type: "tvos_font_selector",
        label: "Title Font TVOS",
        label_tooltip: "Font for the toggle title for TVOS",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "info_label_title_text_font_lg_tv",
        type: "lg_tv_font_selector",
        label: "Title Font LG TV",
        label_tooltip: "Font for the toggle title for LG TV",
        initial_value: "Museo-Bold",
      },
      {
        key: "info_label_title_text_font_samsung_tv",
        type: "samsung_font_selector",
        label: "Title Font Samsung TV",
        label_tooltip: "Font for the toggle title for Samsung TV",
        initial_value: "SamsungOneUI-Bold",
      },
      {
        key: "info_label_title_text_fontsize",
        type: "number_input",
        label: "Font Size",
        initial_value: 40,
      },
      {
        key: "info_label_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        initial_value: 24,
      },
      {
        key: "info_label_description_title_color",
        type: "color_picker_rgba",
        label: "Description Color",
        initial_value: "#161b29B3",
      },
      {
        key: "info_label_description_title_text_font_android_tv",
        type: "android_font_selector",
        label: "Android TV Description Font",
        initial_value: "Roboto-Bold",
      },
      {
        key: "info_label_description_title_text_font_tvos",
        type: "tvos_font_selector",
        label: "TVOS Description Font",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "info_label_description_title_text_font_lg_tv",
        type: "lg_tv_font_selector",
        label: "LG TV Description Font",
        initial_value: "Museo-Bold",
      },
      {
        key: "info_label_description_title_text_font_samsung_tv",
        type: "samsung_font_selector",
        label: "Samsung TV Description Font",
        initial_value: "SamsungOneUI-Bold",
      },
      {
        key: "info_label_description_title_text_fontsize",
        type: "number_input",
        label: "Font Size",
        initial_value: 35,
      },
      {
        key: "info_label_description_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        initial_value: 24,
      },
    ],
  },
  {
    group: true,
    label: "Logout Button Styles",
    tooltip: "These fields affect small logout button styles",
    folded: true,
    fields: [
      {
        key: "button_logout_background_image",
        type: "uploader",
        label: "Button Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_logout_background_image_focused",
        type: "uploader",
        label: "Button Focused Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_logout_width",
        type: "number_input",
        label: "Button Width",
        initial_value: 250,
      },
      {
        key: "button_logout_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        initial_value: 27,
      },
      {
        key: "button_logout_radius",
        type: "number_input",
        label: "Button Radius",
        initial_value: 13,
      },
      {
        key: "button_logout_border",
        type: "number_input",
        label: "Button Border",
        initial_value: 1,
      },
      {
        key: "button_logout_border_color",
        type: "color_picker_rgba",
        label: "Button Border Color",
        initial_value: "#979797ff",
      },
      {
        key: "button_logout_border_color_focused",
        type: "color_picker_rgba",
        label: "Button Border Focused Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_logout_background_color",
        type: "color_picker_rgba",
        label: "Background Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_logout_background_color_focused",
        type: "color_picker_rgba",
        label: "Background Focused Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_logout_title_color",
        type: "color_picker_rgba",
        label: "Title Color",
        initial_value: "#979797FF",
      },
      {
        key: "button_logout_title_color_focused",
        type: "color_picker_rgba",
        label: "Title Focused Color",
        initial_value: "#979797FF",
      },
      {
        key: "button_logout_title_text_font_android_tv",
        type: "android_font_selector",
        label: "Android TV Title Font",
        initial_value: "Roboto-Bold",
      },
      {
        key: "button_logout_title_text_font_tvos",
        type: "tvos_font_selector",
        label: "TVOS Title Font",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "button_logout_title_text_font_lg_tv",
        type: "lg_tv_font_selector",
        label: "LG TV Title Font",
        initial_value: "Museo-Bold",
      },
      {
        key: "button_logout_title_text_font_samsung_tv",
        type: "samsung_font_selector",
        label: "Samsung TV Title Font",
        initial_value: "SamsungOneUI-Bold",
      },
      {
        key: "button_logout_title_text_fontsize",
        type: "number_input",
        label: "Font Size",
        initial_value: 20,
      },
    ],
  },
  {
    group: true,
    label: "Logout Big Button Styles",
    tooltip: "These fields affect big logout button styles",
    folded: true,
    fields: [
      {
        key: "button_logout_big_background_image",
        type: "uploader",
        label: "Button Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_logout_big_background_image_focused",
        type: "uploader",
        label: "Button Focuserd Background Image",
        placeholder: "Upload a file",
      },
      {
        key: "button_logout_big_radius",
        type: "number_input",
        label: "Button Radius",
        initial_value: 13,
      },
      {
        key: "button_logout_big_width",
        type: "number_input",
        label: "Button Width",
        initial_value: 544,
      },
      {
        key: "button_logout_big_bottom_margin",
        type: "number_input",
        label: "Button Bottom Margin",
        initial_value: 27,
      },
      {
        key: "button_logout_big_border",
        type: "number_input",
        label: "Button Border",
        initial_value: 1,
      },
      {
        key: "button_logout_big_border_color",
        type: "color_picker_rgba",
        label: "Button Border Color",
        initial_value: "#979797ff",
      },
      {
        key: "button_logout_big_border_color_focused",
        type: "color_picker_rgba",
        label: "Button Border Focused Color",
        initial_value: "rgba(255,255,255,1)",
      },
      {
        key: "button_logout_big_background_color",
        type: "color_picker_rgba",
        label: "Background Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_logout_big_background_color_focused",
        type: "color_picker_rgba",
        label: "Background Focused Color",
        initial_value: "rgba(255,255,255,0)",
      },
      {
        key: "button_logout_big_title_color",
        type: "color_picker_rgba",
        label: "Title Color",
        initial_value: "#979797FF",
      },
      {
        key: "button_logout_big_title_color_focused",
        type: "color_picker_rgba",
        label: "Title Focused Color",
        initial_value: "#979797FF",
      },
      {
        key: "button_logout_big_title_text_font_android_tv",
        type: "android_font_selector",
        label: "Android TV Title Font",
        initial_value: "Roboto-Bold",
      },
      {
        key: "button_logout_big_title_text_font_tvos",
        type: "tvos_font_selector",
        label: "TVOS Title Font",
        initial_value: "HelveticaNeue-Bold",
      },
      {
        key: "button_logout_big_title_text_font_lg_tv",
        type: "lg_tv_font_selector",
        label: "LG TV Title Font",
        initial_value: "Museo-Bold",
      },
      {
        key: "button_logout_big_title_text_font_samsung_tv",
        type: "samsung_font_selector",
        label: "Samsung TV Title Font",
        initial_value: "SamsungOneUI-Bold",
      },
      {
        key: "button_logout_big_title_text_fontsize",
        type: "number_input",
        label: "Font Size",
        initial_value: 29,
      },
    ],
  },
  {
    group: true,
    label: "Debug",
    tooltip: "For development purposes",
    folded: true,
    fields: [
      {
        type: "tag_select",
        key: "debug_dummy_data_source",
        tooltip_text: "Use dummy data source to test UI",
        options: [
          {
            text: "On",
            value: "on",
          },
          {
            text: "Off",
            value: "off",
          },
        ],
        initial_value: "off",
      },
    ],
  },
];

const Localizations = {
  mobile: {
    fields: [...common, ...mobile],
  },
  tv: {
    fields: [...common, ...tv],
  },
};

module.exports = Localizations;
